# blah

---
  - hosts: loadbalancers
    become: yes
    tasks:
      - name: Install apache
        yum:
          name: httpd
          state: present
      - name: Ensure apache starts
        service:
          name: httpd
          state: started
          enabled: yes

  - hosts: webservers
    become: yes
    tasks:
      - name: Install services
        yum:
          name: 
            - httpd
            - php
          state: present
      - name: Ensure apache starts
        service:
          name: httpd
          state: started
          enabled: yes