# blah

---
  - hosts: loadbalancers
    become: true
    tasks:
      - name: Install apache
        yum:
          name: httpd
          state: present

  - hosts: webservers
    become: true
    tasks:
      - name: Install services
        yum:
          name: 
            - httpd
            - php
          state: present