# blah
---
  - hosts: webservers
    become: yes
    tasks:
      - name: Upload application file
        copy:
          src: ../index.php
          dest: /var/www/html
          mode: 0755
  
      - name: Configure php.ini
        lineinfile:
          path: /etc/php.ini
          regex: ^short_open_tag
          line: 'short_open_tag=On'
      
      - name: Restart apache
        service:
          name: httpd
          state: restarted